### PR TITLE
Adding an alternative "online slug generator" which includes hints an…

### PR DESCRIPTION
**Pull request by bonkersabouttech**
…d tips around optimizing slugs for SEO.

### CODE REVIEW

**Comment by alimony** [comment]
Although I'm not opposed to providing alternatives, I'd like the linked tools to be strictly deterministic about slug generation, i.e. straight conversion with no modifications, including human and/or SEO considerations.

I do appreciate you taking the time to suggest this change though!

**Comment by bonkersabouttech** [comment]
Oh the tool does exactly that.  It just takes a human string and replaces
the spaces with hyphens - that's it.

I've just included some hints and tips on the page around SEO but the tool
itself does a straight conversion with no mods.

**Comment by alimony** [comment]
I'd rather not suggest to users of the tool that they should somehow "improve" the generated slug.

However! I realize just now that the tool I link to serves ads on the same page, and as far as I can tell yours does not. Is that so? I would prefer an ad-free page, and I'll happily replace the current link with yours if that is the case.

**Comment by bonkersabouttech** [comment]
Yep that's correct, my slug generator page does not serve ads.

**Comment by alimony** [comment]
Cool. Could you update this pull request so that the change is simply changing the destination for that link?

**Comment by bonkersabouttech** [comment]
Sure, no worries, will do.

**Comment by alimony** [comment]
Merged and live on the website now, thanks!

**Comment by bonkersabouttech** [comment]
Awesome, many thanks to you too!  Keep up the good work!

**Pull request merged**
